### ISSUE TITLE
Widgetkit Rebuild

### ISSUE THREAD

**Issue by MattMcAdams** [UAB-IT/linear#64]
Complete 3 phase rebuild of widgetkit components.

**Phase 1**
- [x] Change widgetkit spacing styles to use s() units.
- [x] Remove any oddities that would result in layout errors
- [x] Add spacing around the widgetkit components so that they fit into the document flow

**Phase 2**
- [x] Add styles for many options available within widgetkit for theming, keeping the styles consistent to the IT look and feel

**Phase 3**
- [x] Rewrite the positioning logic to perform as expected in instances where it does not
- [x] Rewrite the positioning logic to use CSS Grid after @supports passes
- [x] Write component grid classes to rearrange content into grid areas as needed
